### ISSUE TITLE
[Task] Add locust to docker-compose

### ISSUE THREAD

**Issue by jcadam14** [cfpb/sbl-project#213]
Add the following to docker-compose:
```
  sbl-locust:
    build: ../sbl-filing-api/locust-load-test
    ports:
      - 8089:8089
    env_file:
      - ./dev_setup/common.env
    environment:
      MODE: single
```

This will allow devs to run the locust load tester against the filing-api
